### ISSUE TITLE
UserConsent model missing has_expired method

### ISSUE THREAD

**Issue by rhysmdnz** [catalyst/django-oidc-provider#29]
The UserConsent model has lost it's has_expired method. leading to this error on future attempts to authenticate with an RP you have already authed with.

`AttributeError: 'UserConsent' object has no attribute 'has_expired'`

**Comment by zacps** [comment]
Introduced in 73bb87b7afb69426964d1515cf1e49c212a500c8.

Tests to cover this code path should be added when this is fixed.
